# Generated by Django 6.0.2 on 2026-02-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('COMMERCE', 'Commerce'), ('BUREAU', 'Bureau'), ('HOTEL', 'Hôtel'), ('HALL', 'Hall')], max_length=20)),
                ('categorie_logement', models.CharField(blank=True, choices=[('MAISON_UNI', 'Maison unifamiliale'), ('MAISON_BI', 'Maison bifamiliale'), ('APPART', 'Appartement'), ('AUTRE', 'Autre')], max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Luxembourg', max_length=50)),
                ('surface_habitable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('surface_utile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_terrain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donnees_cadastrales', models.TextField(blank=True)),
                ('annee_construction', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=100)),
                ('loyer_actuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valeur_locative', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valeur_venale_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valeur_reelle', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cpe', models.CharField(blank=True, max_length=100)),
                ('charges_locataire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('investissements_travaux_prevus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('situation_pag_pap', models.TextField(blank=True)),
                ('syndic', models.CharField(blank=True, max_length=255)),
                ('proprietaires', models.ManyToManyField(blank=True, related_name='biens', to='core.proprietaire')),
            ],
        ),
    ]
