# Generated by Django 6.0.2 on 2026-02-15 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bien'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierViager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_viager', models.CharField(choices=[('CLASSIQUE_OCCUPE', 'Viager classique occupé'), ('CLASSIQUE_LIBRE', 'Viager classique libre'), ('LONG_TERME', 'Viager long terme')], max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('description_interne', models.TextField(blank=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='core.bien')),
            ],
        ),
    ]
