# Generated by Django 6.0.2 on 2026-02-15 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dossierviager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioViager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_scenario', models.CharField(blank=True, max_length=100)),
                ('type_scenario', models.CharField(choices=[('CLASSIQUE', 'Viager classique'), ('TEMPORAIRE', 'Rente temporaire'), ('MIXTE', 'Mixte (temporaire + viagère)')], default='CLASSIQUE', max_length=20)),
                ('bouquet_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bouquet_montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rente_viagere_mensuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duree_rente_temporaire_annees', models.IntegerField(blank=True, null=True)),
                ('tri', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('van', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('statut', models.CharField(choices=[('EN_SUSPENS', 'En suspens'), ('ACQUIS', 'Acquis'), ('REFUS_VENDEUR', 'Refus vendeur'), ('REFUS_ACQUEREUR', 'Refus acquéreur')], default='EN_SUSPENS', max_length=20)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.dossierviager')),
            ],
        ),
    ]
