# Generated by Django 6.0.2 on 2026-02-17 08:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scenarioviager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresPays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(choices=[('LU', 'Luxembourg'), ('DE', 'Allemagne')], max_length=2, unique=True)),
                ('entretien_annuel_proprietaire', models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=5)),
                ('frais_fixes_proprietaire', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=5)),
                ('appreciation_valeur_immo', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('taux_bce', models.DecimalField(decimal_places=2, default=Decimal('2.15'), max_digits=4)),
                ('majoration_risque', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=4)),
                ('rendement_cible', models.DecimalField(decimal_places=2, default=Decimal('4.65'), max_digits=4)),
                ('frais_fis_annuel', models.DecimalField(decimal_places=2, default=Decimal('0.60'), max_digits=4)),
                ('frais_gm_annuel', models.DecimalField(decimal_places=2, default=Decimal('0.75'), max_digits=4)),
                ('frais_compte_bancaire', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4)),
                ('frais_agence', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=4)),
                ('frais_notaire', models.DecimalField(decimal_places=2, default=Decimal('7.50'), max_digits=4)),
                ('ouverture_dossier_fis', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10)),
                ('ouverture_dossier_gm', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
            ],
        ),
    ]
