# Generated by Django 6.0.2 on 2026-02-18 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parametrespays'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierviager',
            name='parametres_pays',
            field=models.ForeignKey(blank=True, help_text='Paramètres standards du pays (taux, frais, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.parametrespays'),
        ),
    ]
