# Generated by Django 6.0.2 on 2026-02-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dossierviager_parametres_pays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrespays',
            options={'verbose_name': 'Paramètres pays', 'verbose_name_plural': 'Paramètres pays'},
        ),
        migrations.AddField(
            model_name='scenarioviager',
            name='enveloppe_credirestier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='scenarioviager',
            name='investissement_initial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
