# Generated by Django 6.0.2 on 2026-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_parametrespays_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioviager',
            name='respecte_plafond_60',
            field=models.BooleanField(default=True),
        ),
    ]
