# Generated by Django 6.0.2 on 2026-02-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scenarioviager_respecte_plafond_60'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenarioviager',
            old_name='enveloppe_credirestier',
            new_name='enveloppe_credirentier',
        ),
    ]
