# Generated by Django 6.0.2 on 2026-02-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_enveloppe_credirestier_scenarioviager_enveloppe_credirentier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenarioviager',
            old_name='bouquet_percent',
            new_name='bouquet_pourcent',
        ),
    ]
