# Generated by Django 6.0.2 on 2026-02-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_bouquet_percent_scenarioviager_bouquet_pourcent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioviager',
            name='cout_annuel_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
