# Generated by Django 6.0.2 on 2026-02-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_scenarioviager_cout_annuel_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableEsperanceVie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(choices=[('LU', 'Luxembourg'), ('DE', 'Allemagne')], help_text='Code pays (LU, DE).', max_length=2)),
                ('source_officielle', models.CharField(help_text='Exemple: STATEC, Destatis, etc.', max_length=100)),
                ('annee_reference', models.IntegerField(help_text='Année de référence de la table officielle (ex: 2023).')),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('A', 'Autre / Non précisé')], help_text='Sexe de la personne.', max_length=1)),
                ('age', models.PositiveIntegerField(help_text='Âge en années révolues (0 à 120).')),
                ('esperance_vie_restante', models.DecimalField(decimal_places=2, help_text='Espérance de vie restante à cet âge (en années, ex: 23.45).', max_digits=5)),
                ('date_publication_source', models.DateField(help_text="Date de publication de la table par l'organisme officiel.")),
                ('date_import', models.DateTimeField(auto_now_add=True, help_text="Date de l'import dans ApexViager.")),
                ('actif', models.BooleanField(default=True, help_text='Cocher pour indiquer que cette table est active.')),
            ],
            options={
                'verbose_name': "Table d'espérance de vie",
                'verbose_name_plural': "Tables d'espérance de vie",
                'unique_together': {('pays', 'annee_reference', 'sexe', 'age')},
            },
        ),
    ]
