# Generated by Django 6.0.2 on 2026-02-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tableesperancevie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableesperancevie',
            name='age_signature',
            field=models.PositiveIntegerField(blank=True, help_text='Âge du crédirentier à la date de signature.', null=True),
        ),
        migrations.AddField(
            model_name='tableesperancevie',
            name='date_signature',
            field=models.DateField(blank=True, help_text="Date de signature de l'acte de viager.", null=True),
        ),
        migrations.AddField(
            model_name='tableesperancevie',
            name='esperance_vie_signature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Espérance de vie restante (en années) à la date de signature.', max_digits=5, null=True),
        ),
    ]
