# Generated by Django 6.0.2 on 2026-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dossierviager_age_signature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossierviager',
            options={'verbose_name': 'Dossier de viager', 'verbose_name_plural': 'Dossiers de viager'},
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='age_actuel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='esperance_vie',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
