# Generated by Django 6.0.2 on 2026-03-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_dossierviager_options_proprietaire_age_actuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='canton_etat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Canton/État fédéral'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='code_postal',
            field=models.CharField(blank=True, max_length=6, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='pays',
            field=models.CharField(choices=[('Luxembourg', 'Luxembourg'), ('Allemagne', 'Allemagne')], default='Luxembourg', max_length=20, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='rue_numero',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rue et numéro'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
    ]
