# Generated by Django 6.0.2 on 2026-03-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_proprietaire_canton_etat_proprietaire_code_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableesperancevie',
            name='annee_reference',
            field=models.IntegerField(help_text='Année de référence de la table officielle (ex : 2023).'),
        ),
        migrations.AlterField(
            model_name='tableesperancevie',
            name='esperance_vie_restante',
            field=models.DecimalField(decimal_places=2, help_text='Espérance de vie restante à cet âge (en années, ex : 23.45).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tableesperancevie',
            name='pays',
            field=models.CharField(choices=[('Luxembourg', 'Luxembourg'), ('Allemagne', 'Allemagne')], help_text='Pays (Luxembourg, Allemagne).', max_length=20),
        ),
        migrations.AlterField(
            model_name='tableesperancevie',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], help_text='Sexe de la personne.', max_length=10),
        ),
        migrations.AlterField(
            model_name='tableesperancevie',
            name='source_officielle',
            field=models.CharField(help_text='Exemple : STATEC, Destatis, etc.', max_length=100),
        ),
    ]
