# Generated by Django 6.0.2 on 2026-03-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tableesperancevie_annee_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraitCadastral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(choices=[('LU', 'Luxembourg'), ('DE', 'Allemagne')], default='LU', max_length=2)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='extraits_cadastraux/')),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraits_cadastraux', to='core.bien')),
            ],
        ),
    ]
