# Generated by Django 6.0.2 on 2026-03-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_extraitcadastral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcelle', models.CharField(max_length=50)),
                ('lieudit', models.CharField(blank=True, max_length=100)),
                ('nature', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('quote_part', models.CharField(blank=True, max_length=20)),
                ('contenance', models.CharField(blank=True, max_length=20)),
                ('revenu_bati_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenu_non_bati_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('extrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='core.extraitcadastral')),
            ],
        ),
    ]
