# Generated by Django 6.0.2 on 2026-03-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_parcelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='donnees_cadastrales',
        ),
    ]
